import React, { useState, useCallback } from 'react';
import { AuthState, User, AuthView, Tool, HistoryEntry } from './types';
import Login from './components/auth/Login';
import Register from './components/auth/Register';
import AdminLogin from './components/auth/AdminLogin';
import Dashboard from './components/dashboard/Dashboard';
import AdminPanel from './components/admin/AdminPanel';
import UserHistoryPage from '../pages/UserHistoryPage';
import UserProfilePage from '../pages/UserProfilePage';
import { ALL_TOOLS, createActivePlaceholder } from './constants';
import * as Icons from './components/icons/toolIcons';


const App: React.FC = () => {
  const [authState, setAuthState] = useState<AuthState>({
    isAuthenticated: false,
    user: null,
    isAdmin: false,
  });
  const [authView, setAuthView] = useState<AuthView>(AuthView.LOGIN);
  const [tools, setTools] = useState<Tool[]>(ALL_TOOLS);
  const [history, setHistory] = useState<HistoryEntry[]>([]);
  const [userView, setUserView] = useState<'dashboard' | 'history' | 'profile'>('dashboard');

  const handleLogin = useCallback((user: User, isAdmin = false) => {
    setAuthState({ isAuthenticated: true, user, isAdmin });
  }, []);

  const handleLogout = useCallback(() => {
    setAuthState({ isAuthenticated: false, user: null, isAdmin: false });
    setAuthView(AuthView.LOGIN);
    setUserView('dashboard');
  }, []);

  const handleToolToggle = useCallback((toolId: string) => {
    setTools(prevTools =>
      prevTools.map(tool =>
        tool.id === toolId ? { ...tool, enabled: !tool.enabled } : tool
      )
    );
  }, []);

  const addToHistory = useCallback((entry: Omit<HistoryEntry, 'id' | 'timestamp'>) => {
    const newEntry: HistoryEntry = {
      ...entry,
      id: `${Date.now()}-${Math.random()}`,
      timestamp: new Date(),
    };
    setHistory(prevHistory => [...prevHistory, newEntry]);
  }, []);

  const handleToolAdd = useCallback((name: string, category: string) => {
    const newTool: Tool = createActivePlaceholder({
      id: `custom_${name.toLowerCase().replace(/\s+/g, '_')}_${Date.now()}`,
      name,
      category,
      description: `A custom tool generated by the admin: ${name}`,
      icon: Icons.PlaceholderIcon,
    });
    setTools(prev => [...prev, newTool]);
  }, []);

  const renderAuthView = () => {
    switch (authView) {
      case AuthView.LOGIN:
        return <Login onLogin={handleLogin} setView={setAuthView} />;
      case AuthView.REGISTER:
        return <Register onRegister={() => setAuthView(AuthView.LOGIN)} setView={setAuthView} />;
      case AuthView.ADMIN_LOGIN:
        return <AdminLogin onLogin={handleLogin} setView={setAuthView} />;
      default:
        return <Login onLogin={handleLogin} setView={setAuthView} />;
    }
  };
  
  const mainContent = () => {
    if (!authState.isAuthenticated) {
      return (
        <div className="min-h-screen bg-transparent flex items-center justify-center p-4">
          {renderAuthView()}
        </div>
      );
    }
  
    if (authState.isAdmin) {
      return <AdminPanel 
        user={authState.user!} 
        onLogout={handleLogout} 
        tools={tools} 
        onToolToggle={handleToolToggle} 
        onToolAdd={handleToolAdd}
        history={history}
        addToHistory={addToHistory}
      />;
    }
    
    const enabledTools = tools.filter(tool => tool.enabled);
  
    if (userView === 'history') {
      return <UserHistoryPage 
                user={authState.user!}
                onLogout={handleLogout}
                history={history.filter(h => h.context !== 'admin')} 
                onBack={() => setUserView('dashboard')}
             />;
    }
  
    if (userView === 'profile') {
      return <UserProfilePage 
                user={authState.user!}
                onLogout={handleLogout}
                onBack={() => setUserView('dashboard')}
             />;
    }
  
    return <Dashboard 
              user={authState.user!} 
              onLogout={handleLogout} 
              tools={enabledTools} 
              onShowHistory={() => setUserView('history')}
              onShowProfile={() => setUserView('profile')}
              addToHistory={addToHistory}
           />;
  }

  return (
    <main>
        <div className="animated-bg"></div>
        {mainContent()}
    </main>
  );
};

export default App;